import './globals.css'
import { Inter } from 'next/font/google'
import Toastify from "../components/Toastify";
import { GlobalProvider } from "../context/GlobalContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <Toastify />
          {children}
        </GlobalProvider>
      </body>
    </html>
  )
}
